typography_spectrum: 0.17418248229660094
color:
  brandColors:
    - '#010101'
    - '#ebeff3'
    - '#6e717c'
    - '#ac857e'
    - '#9ea4ae'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.4708686275407672
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9994
analytics:
  google: null
  facebook: null
  twitter: null
name: Tellman
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: I AM TELLMAN
description: SHABAMBO
purpose: []
